### PR TITLE
Set up Emotion

### PR DESCRIPTION
**Pull request by colebemis**

### CODE REVIEW

**Comment by colebemis** [comment]
The deploy is currently broken ([link](https://dasher-gzf368but.now.sh/))
image


I checked the Now logs and found this error:
```
TypeError: Cannot read property 'key' of undefined
    at Object.t.insertStyles (/var/task/.next/server/static/8WbSJ8o7NYgE7yyeAezKX/pages/index.js:1:1357)
    at g (/var/task/.next/server/static/8WbSJ8o7NYgE7yyeAezKX/pages/index.js:22:138664)
    at /var/task/.next/server/static/8WbSJ8o7NYgE7yyeAezKX/pages/index.js:22:139223
    at Object.children (/var/task/.next/server/static/8WbSJ8o7NYgE7yyeAezKX/pages/index.js:22:138326)
    at ReactDOMServerRenderer.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3292:55)
    at ReactDOMServerRenderer.read (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3059:29)
    at renderToString (/var/task/node_modules/react-dom/cjs/react-dom-server.node.development.js:3526:27)
    at render (/var/task/node_modules/next-server/dist/server/render.js:45:16)
    at renderPage (/var/task/node_modules/next-server/dist/server/render.js:112:16)
```

Here are the relevant version numbers:
```
now 12.1.14
next 7.0.2
@emotion/babel-preset-css-prop 10.0.5
@emotion/core 10.0.5
```

I'm not sure how to fix this error. The app works fine locally and I couldn't find any similar issues online.  Any ideas? @tkh44 @rauchg @paulogdm

**Comment by tkh44** [comment]
Can you try moving the emotion preset to the first entry in the plugins list. Not sure but worth a shot

**Comment by colebemis** [comment]
@tkh44 Putting `@emotion/babel-preset-css-prop` as the first preset actually broke emotion locally. I also tried building and serving the app locally with `NODE_ENV` set to `production` and it still worked. Any other ideas?

**Comment by DennisKo** [comment]
Randomly noticed your problem on spectrum. We have a pretty smilliar setup and emotion is working for me -> https://github.com/DennisKo/zeit-now-next-apollo-typescript-example/pull/1 . Maybe you can find the problem while comparing our implementations. Note: every commit in that PR deployed and worked correctly for me...

**Comment by colebemis** [comment]
@DennisKo Thanks so much! I identified that the problem is related to the `withApollo` HOC. When I remove `withApollo` from `_app.js`, the error goes away. However, I updated my code to match yours almost exactly and I'm still getting the same error. I'm going to try copying your code line-by-line and see if I can narrow down the problem. It's frustrating because I can't replicate the error locally so I have to keep deploying to debug 😓

**Comment by colebemis** [comment]
@DennisKo I checked out your repo and found that adding a div with a `css` prop around the `Query` component causes the same deploy error I'm getting:

```diff
import { Query } from "react-apollo";
import gql from "graphql-tag";
import * as React from "react";
import { BooksQuery } from "../__generated__/BooksQuery";

const booksQuery = gql`
  query BooksQuery {
    books {
      title
      author
    }
  }
`;

export default class BookList extends React.Component<{}, {}> {
  render() {
    return (
+     <div css={{ backgroundColor: 'papaywhip' }}>
        <Query<BooksQuery> query={booksQuery}>
          {({ loading, error, data: { books } }) => {
            if (error) return <div>{JSON.stringify(error)}</div>;
            if (loading) return <div>Loading</div>;

            return (
              <section>
                <ul>
                  {books.map((book, index) => (
                    <li
                      css={{
                        color: "hotpink",
                        "&:hover": {
                          color: "darkorchid"
                        }
                      }}
                      key={book.title}
                    >
                      <span>{index + 1}. </span>
                      <div>{book.title}</div>
                      <div>{book.author}</div>
                    </li>
                  ))}
                </ul>
              </section>
            );
          }}
        </Query>
+     </div>
    );
  }
}
```

**Comment by colebemis** [comment]
I'd really like to use emotion because of the zero-config SSR and first-class `css` prop support but this issue is showstopper for me. I think I'm going to move forward with styled-components for now: https://github.com/colebemis/dasher-demo/pull/6

**Comment by paulogdm** [comment]
Hello! Is this a now specific error? Anything I can help with?

**Comment by colebemis** [comment]
@paulogdm Do you have any insight into why [this error](https://github.com/colebemis/dasher-demo/pull/5#issuecomment-449440660) is only occurring when deployed with now? I tried building and serving the app locally with `NODE_ENV` set to `production` and I still didn't get an error.

I figured out that the combination of using server-side rendered Apollo Client and Emotion is causing the error, but it's hard to tell how to fix it.

**Pull request closed without merging**
